[development]
database_url = "mysql://test:test@localhost/test"
#json_logging = false
sentry_dsn = "https://xxx@sentry.prod.mozaws.net/58"

# Auth tokens for broadcasters and readers of broadcasts
[development.broadcaster_auth]
#kinto = [
#  "token1",
#  "token2"
#]
#atmo = ["token3"]

[development.reader_auth]
#autopush_rs = ["token4"]


[staging]
#database_url = "mysql://"
json_logging = true

[staging.broadcaster_auth]

[staging.reader_auth]


[production]
#database_url = "mysql://"
json_logging = true

[production.broadcaster_auth]

[production.reader_auth]
